name: Measure coverage

# on:
#   pull_request:

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  continuos-integration:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    name: Deploy
    runs-on: ubuntu-latest
  # build:
  #   runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew  # Concede permissões de execução
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport
        
      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          #token: ${{ secrets.ACTIONS_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
