name: Android Unit Tests

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'  # ou a versão que você está usando no projeto

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew  # Concede permissões de execução

    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Run tests and save results
      run: |
        ./gradlew test > test_output.txt
        total_tests=$(grep -o "Tests run: [0-9]*" test_output.txt | awk -F ": " '{sum+=$2} END{print sum}')
        successful_tests=$(grep -o "OK \([0-9]* tests\)" test_output.txt | awk '{sum+=$1} END{print sum}')
        percentage=$((successful_tests * 100 / total_tests))
        echo "Porcentagem de testes bem-sucedidos: $percentage%"



    # - name: Run tests
    #   run: ./gradlew test

    # - name: Calculate test coverage
    #   run: ./gradlew jacocoTestReport

    # - name: Display test coverage percentage
    #   run: |
    #     grep "Overall coverage" app/build/reports/jacoco/jacocoTestReport/html/index.html | \
    #     sed -E 's/<[^>]+>//g' | awk '{print $3}'
