name: Run Android Unit Tests

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission to the script
      run: chmod +x run_tests.sh
      
    - name: Run Tests
      run: ./run_tests.sh
